controller_manager:
  ros__parameters:
    update_rate: 250
    gripper_action_controller_position:
      type: position_controllers/GripperActionController
    joint_state_broadcaster:
      type: joint_state_broadcaster/JointStateBroadcaster
    joint_group_position_controller:
      type: position_controllers/JointGroupPositionController
gripper_action_controller_position:
  ros__parameters:
    action_monitor_rate: 20.0
    allow_stalling: false
    goal_tolerance: 0.01
    joint: null
    max_effort: 0.0
    stall_timeout: 1.0
    stall_velocity_threshold: 0.001
joint_state_broadcaster:
  ros__parameters:
    map_interface_to_joint_state.effort: effort
    map_interface_to_joint_state.position: position
    map_interface_to_joint_state.velocity: velocity
    use_local_topics: false
    use_urdf_to_filter: true
joint_group_position_controller:
  ros__parameters: {}
